# Generated by Django 4.2.5 on 2023-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0002_auto_20211217_0041"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldsetsAdminModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("middle_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name="customadminmodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customadminmodel2",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="inheritedadminmodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
